spring.application.name=Projeto01Grupo03

# Configuracoes do Banco de Dados MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/grupo03_db?createDatabaseIfNotExist=true&serverTimezone=America/Manaus
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true